algoritmo "Entrada por idade"
// Autor: Thiago Marcelino Vieira
// Data: 14/04/2026
var
// As variáveis serão escritas abaixo
   idade: real
inicio
    // Entrada
    escreval("Digite a idade do visitante")
    leia(idade)

   // Processo
   limpatela
   se (idade < 5) ou (idade >= 65) entao
      // Saída
      escreva("A entrada do visitante será gratuita.")
   senao
      escreva("A entrada do visitante será paga.")
   fimse
fimalgoritmo
